name: 'Import Solution File'
description: 'Imports a solution file to a Microsoft Dynamics Instance'
branding:
  icon: 'arrow-up-right'
  color: 'blue'
inputs:
    dynamics-url:
        description: 'The URL of your Microsoft Dynamics instance'
        required: true
    application-id:
        description: 'The Application ID of your Azure AD application connected to your Microsoft Dynamics instance app user'
        required: true
    application-secret:
        description: 'The Application Secret of your Azure AD application connected to your Microsoft Dynamics instance app user'
        required: true
    tenant-id:
        description: 'The Tenant ID of your Azure AD application connected to your Microsoft Dynamics instance app user'
        required: true
    solution-file:
        description: 'The file path or base64 encoded string of the solution file to be imported'
        required: true
runs:
  using: "composite"
  steps:

    - name: Setup PHP
      uses: shivammathur/setup-php@v2
      with:
        php-version: '8.2'

    - name: Install Dependencies
      shell: bash
      run: composer install -d "$GITHUB_ACTION_PATH/src/" -o

    - name: Publish all changes
      shell: bash
      env:
        INSTANCE_URL: ${{ inputs.dynamics-url }}
        APPLICATION_ID: ${{ inputs.application-id }}
        APPLICATION_SECRET: ${{ inputs.application-secret }}
        TENANT_ID: ${{ inputs.tenant-id }}
        SOLUTION_FILE: ${{ inputs.solution-file }}
      run: php "$GITHUB_ACTION_PATH/src/index.php"
